###findCurrentWeather
GET http://localhost:8080/weather
Accept: application/json

###findAverageWeather
POST http://localhost:8080/weather
Content-Type: application/json

{
  "from": "2023-03-18",
  "to": "2023-03-20"
}
